import type { CompileResult, CompileAndEvalResult } from './types.js';

export function generateHtmlReport(
  result: CompileResult,
  evalResult?: CompileAndEvalResult,
): string {
  const changesRows = result.changes
    .map(
      (c) => `
      <tr>
        <td><code>${escapeHtml(c.kind)}</code></td>
        <td>${escapeHtml(c.description)}</td>
        <td>${c.before ? escapeHtml(c.before) : '-'}</td>
        <td>${c.after ? escapeHtml(c.after) : '-'}</td>
      </tr>`,
    )
    .join('');

  const evalSection = evalResult
    ? `
    <h2>Evaluation Results</h2>
    <div class="metrics">
      <div class="metric">
        <span class="label">Original Score</span>
        <span class="value">${evalResult.originalScore.toFixed(3)}</span>
      </div>
      <div class="metric">
        <span class="label">Compiled Score</span>
        <span class="value">${evalResult.compiledScore.toFixed(3)}</span>
      </div>
      <div class="metric">
        <span class="label">Actual Delta</span>
        <span class="value ${evalResult.actualDelta >= 0 ? 'positive' : 'negative'}">${evalResult.actualDelta >= 0 ? '+' : ''}${evalResult.actualDelta.toFixed(3)}</span>
      </div>
    </div>
    <table>
      <thead><tr><th>Task</th><th>Original</th><th>Compiled</th><th>Delta</th></tr></thead>
      <tbody>
        ${evalResult.perTask
          .map(
            (t) => `
          <tr>
            <td>${escapeHtml(t.task)}</td>
            <td>${t.original.toFixed(3)}</td>
            <td>${t.compiled.toFixed(3)}</td>
            <td class="${t.delta >= 0 ? 'positive' : 'negative'}">${t.delta >= 0 ? '+' : ''}${t.delta.toFixed(3)}</td>
          </tr>`,
          )
          .join('')}
      </tbody>
    </table>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>promptc Compilation Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }
    h1 { border-bottom: 2px solid #2563eb; padding-bottom: 0.5rem; }
    h2 { color: #2563eb; margin-top: 2rem; }
    .metrics { display: flex; gap: 1.5rem; margin: 1rem 0; flex-wrap: wrap; }
    .metric { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1rem 1.5rem; min-width: 140px; }
    .metric .label { display: block; font-size: 0.85rem; color: #64748b; }
    .metric .value { display: block; font-size: 1.5rem; font-weight: 600; margin-top: 0.25rem; }
    .positive { color: #16a34a; }
    .negative { color: #dc2626; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background: #f1f5f9; font-weight: 600; }
    code { background: #f1f5f9; padding: 0.15rem 0.4rem; border-radius: 4px; font-size: 0.9em; }
    .warnings { background: #fef3c7; border: 1px solid #fbbf24; border-radius: 8px; padding: 1rem; margin: 1rem 0; }
    footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 0.85rem; }
  </style>
</head>
<body>
  <h1>promptc Compilation Report</h1>

  <h2>Summary</h2>
  <div class="metrics">
    <div class="metric">
      <span class="label">Token Reduction</span>
      <span class="value">${result.tokenReductionPct.toFixed(1)}%</span>
    </div>
    <div class="metric">
      <span class="label">Quality Delta</span>
      <span class="value ${result.qualityDelta >= 0 ? 'positive' : 'negative'}">${result.qualityDelta >= 0 ? '+' : ''}${result.qualityDelta.toFixed(3)}</span>
    </div>
    <div class="metric">
      <span class="label">Safety Similarity</span>
      <span class="value">${result.safetySimilarity.toFixed(3)}</span>
    </div>
    <div class="metric">
      <span class="label">Changes Made</span>
      <span class="value">${result.changes.length}</span>
    </div>
  </div>

  ${result.warnings.length > 0 ? `<div class="warnings"><strong>Warnings:</strong><ul>${result.warnings.map((w) => `<li>${escapeHtml(w)}</li>`).join('')}</ul></div>` : ''}

  ${
    result.changes.length > 0
      ? `
  <h2>Changes</h2>
  <table>
    <thead><tr><th>Type</th><th>Description</th><th>Before</th><th>After</th></tr></thead>
    <tbody>${changesRows}</tbody>
  </table>`
      : ''
  }

  ${evalSection}

  <footer>Generated by promptc v0.3.0</footer>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
